/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check (public) */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my question bank items */
        get: operations["BankItemsController_list"];
        put?: never;
        /** Add a complete question to my bank */
        post: operations["BankItemsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bank-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BankItemsController_findOne"];
        put?: never;
        post?: never;
        /** Delete from bank (quiz copies are kept) */
        delete: operations["BankItemsController_remove"];
        options?: never;
        head?: never;
        patch: operations["BankItemsController_update"];
        trace?: never;
    };
    "/api/v1/game-histories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finished games I played with my account (newest first) */
        get: operations["GameHistoriesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-histories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My result in one finished game with per-question review */
        get: operations["GameHistoriesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finished games I hosted (ADMIN: all) */
        get: operations["GameReportsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report of one finished game (players + per-question stats) */
        get: operations["GameReportsController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-reports/{id}/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One player in a finished game I hosted: result + per-question answers */
        get: operations["GameReportsController_findPlayer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Host: my game rooms · Player: find a joinable room with ?gamePin= */
        get: operations["GameSessionsController_list"];
        put?: never;
        /** Open a game room from a published quiz */
        post: operations["GameSessionsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current game state (host or joined player view) */
        get: operations["GameSessionsController_findOne"];
        put?: never;
        post?: never;
        /** Close and delete a game room (its report is deleted too) */
        delete: operations["GameSessionsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host skips ahead: close answers now → leaderboard → next question */
        post: operations["GameSessionsController_advance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an answer to the current question (once per question) */
        post: operations["GameSessionsController_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live game state stream (text/event-stream) */
        get: operations["GameSessionsController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a room in the lobby (re-joining returns the same player) */
        post: operations["GameSessionsController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Leave the lobby (player) or remove a player (host) */
        delete: operations["GameSessionsController_removePlayer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game-sessions/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Host starts the game (3-2-1 countdown, then question 1) */
        post: operations["GameSessionsController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guest: find the room waiting for players with ?gamePin= */
        get: operations["GuestGamesController_lobby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-games/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guest: current game state (room pass required) */
        get: operations["GuestGamesController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-games/{id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guest: submit an answer to the current question */
        post: operations["GuestGamesController_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-games/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Guest: live game state stream (text/event-stream) */
        get: operations["GuestGamesController_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-games/{id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guest: join a room in the lobby — sets the room pass cookie (HttpOnly) */
        post: operations["GuestGamesController_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/guest-games/{id}/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Guest: leave the lobby (own player only) */
        delete: operations["GuestGamesController_leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user from the verified Core Hub token */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/game-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My overall stats across finished games */
        get: operations["GameStatsController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quizzes (own; ADMIN sees all) */
        get: operations["QuizzesController_list"];
        put?: never;
        /** Create a draft quiz */
        post: operations["QuizzesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a quiz with its questions */
        get: operations["QuizzesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a quiz (played games and reports are kept) */
        delete: operations["QuizzesController_remove"];
        options?: never;
        head?: never;
        /** Update title/description/status and/or replace all questions */
        patch: operations["QuizzesController_update"];
        trace?: never;
    };
    "/api/v1/quizzes/{id}/copies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Copy a quiz into a new draft owned by the caller */
        post: operations["QuizzesController_copy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnswerReceiptView: {
            /** @description ผลถูก/ผิดเปิดเผยตอนเฉลย ผ่าน state */
            accepted: boolean;
            /** Format: uuid */
            optionId: string;
            questionIndex: number;
        };
        AnswerReviewOptionView: {
            isCorrect: boolean;
            /** Format: uuid */
            optionId: string;
            text: string;
        };
        AnswerReviewView: {
            earnedPoints: number;
            imageUrl?: string | null;
            options: components["schemas"]["AnswerReviewOptionView"][];
            /** @description คะแนนเต็มของข้อ */
            points: number;
            prompt: string;
            /** Format: uuid */
            questionId: string;
            /** @description ลำดับเริ่มที่ 1 */
            questionNumber: number;
            /** @description มิลลิวินาที · null = ไม่ได้ตอบ */
            responseMs?: number | null;
            /** @enum {string} */
            result: "CORRECT" | "INCORRECT" | "TIMEOUT" | "NO_ANSWER";
            /** Format: uuid */
            selectedOptionId?: string | null;
            /** @description วินาที */
            timeLimit: number;
            type: string;
        };
        BankItemView: {
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** Format: uuid */
            id: string;
            imageUrl?: string | null;
            options: components["schemas"]["OptionView"][];
            ownerCoreUserId: string;
            points: number;
            prompt: string;
            tags: string[];
            timeLimit: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "TRUE_FALSE";
            /** Format: date-time */
            updatedAt: string;
            /** @description จำนวนครั้งที่ถูกคัดลอกไปใช้ในแบบทดสอบ */
            usedCount: number;
        };
        CreateBankItemDto: {
            /**
             * @default MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** @description ลิงก์รูปภาพ https:// เท่านั้น */
            imageUrl?: string | null;
            options: components["schemas"]["OptionInputDto"][];
            /** @description 0 = ไม่คิดคะแนน */
            points: number;
            /** @description แบบร่างเว้นว่างได้ แต่เผยแพร่ต้องมี */
            prompt: string;
            tags?: string[];
            /** @description วินาที */
            timeLimit: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "TRUE_FALSE";
        };
        CreateGameSessionDto: {
            /**
             * Format: uuid
             * @description แบบทดสอบที่เผยแพร่แล้ว และคำถามครบทุกข้อ
             */
            quizId: string;
            /** @default false */
            shuffleOptions: boolean;
            /** @default false */
            shuffleQuestions: boolean;
            /** @description ตั้งเวลาเท่ากันทุกข้อ (วินาที) · null = ใช้เวลาที่ตั้งในแต่ละข้อ */
            timeLimitOverride?: number | null;
        };
        CreateQuizDto: {
            description?: string;
            title: string;
        };
        GameJoinView: {
            avatarIndex: number;
            /** Format: uuid */
            gameSessionId: string;
            nickname: string;
            /** Format: uuid */
            playerId: string;
        };
        GameLobbyView: {
            gamePin: string;
            /** Format: uuid */
            id: string;
            /** @description ผู้เรียกเข้าห้องนี้แล้ว */
            joined: boolean;
            playerCount: number;
            quizTitle: string;
            /** @enum {string} */
            status: "LOBBY" | "ACTIVE" | "FINISHED" | "CANCELLED";
            totalQuestions: number;
        };
        GameMeView: {
            answer?: components["schemas"]["GameMyAnswerView"] | null;
            avatarIndex: number;
            nickname: string;
            /** Format: uuid */
            playerId: string;
            rank: number;
            score: number;
            streak: number;
        };
        GameMyAnswerView: {
            /** @description หลังเฉลยเท่านั้น */
            isCorrect?: boolean;
            isTimedOut: boolean;
            /** Format: uuid */
            optionId?: string | null;
            /** @description หลังเฉลยเท่านั้น */
            points?: number;
        };
        GameOptionView: {
            /** Format: uuid */
            id: string;
            /** @description ผู้เล่นเห็นเฉพาะหลังเฉลย (RESULT ขึ้นไป) · host เห็นตลอด */
            isCorrect?: boolean;
            text: string;
        };
        GamePlayerView: {
            avatarIndex: number;
            /** @description ตอบข้อปัจจุบันแล้ว */
            hasAnswered: boolean;
            /** Format: uuid */
            id: string;
            nickname: string;
            rank: number;
            score: number;
            /** @description ตอบถูกติดกันตอนนี้ */
            streak: number;
        };
        GameQuestionView: {
            /** Format: uuid */
            id: string;
            imageUrl?: string | null;
            /** @description ลำดับเริ่มที่ 0 */
            index: number;
            options: components["schemas"]["GameOptionView"][];
            points: number;
            prompt: string;
            timeLimit: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "TRUE_FALSE";
        };
        GameReportSummaryView: {
            /** @description เปอร์เซ็นต์ตอบถูกเฉลี่ย 0–100 */
            averageAccuracy: number;
            /** Format: date-time */
            finishedAt: string;
            gamePin: string;
            /**
             * Format: uuid
             * @description id ของห้องเกม
             */
            id: string;
            playerCount: number;
            questionCount: number;
            /** Format: uuid */
            quizId?: string | null;
            quizTitle: string;
            /** Format: date-time */
            startedAt?: string | null;
            topScore: number;
        };
        GameReportView: {
            /** @description เปอร์เซ็นต์ตอบถูกเฉลี่ย 0–100 */
            averageAccuracy: number;
            /** Format: date-time */
            finishedAt: string;
            gamePin: string;
            /**
             * Format: uuid
             * @description id ของห้องเกม
             */
            id: string;
            playerCount: number;
            players: components["schemas"]["ReportPlayerView"][];
            questionCount: number;
            questions: components["schemas"]["ReportQuestionView"][];
            /** Format: uuid */
            quizId?: string | null;
            quizTitle: string;
            /** Format: date-time */
            startedAt?: string | null;
            topScore: number;
        };
        GameSessionSummaryView: {
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            gamePin: string;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            phase: "LOBBY" | "QUESTION" | "RESULT" | "LEADERBOARD" | "PODIUM";
            playerCount: number;
            /** Format: uuid */
            quizId?: string | null;
            quizTitle: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** @enum {string} */
            status: "LOBBY" | "ACTIVE" | "FINISHED" | "CANCELLED";
            totalQuestions: number;
        };
        GameSettingsView: {
            shuffleOptions: boolean;
            shuffleQuestions: boolean;
            timeLimitOverride?: number | null;
        };
        GameStateView: {
            answeredCount: number;
            /**
             * Format: date-time
             * @description นับถอยหลังเต็มจอ: ปิดรับคำตอบ (QUESTION) หรือ ข้อถัดไป/ประกาศผล (LEADERBOARD)
             */
            countdownEndsAt?: string | null;
            /** Format: date-time */
            createdAt: string;
            currentQuestionIndex: number;
            /** @description จำนวนคนที่เลือกแต่ละตัวเลือก { optionId: count } — ผู้เล่นเห็นหลังเฉลย */
            distribution?: {
                [key: string]: number;
            } | null;
            /** Format: date-time */
            finishedAt?: string | null;
            gamePin: string;
            /** Format: uuid */
            id: string;
            me?: components["schemas"]["GameMeView"] | null;
            /** @enum {string} */
            phase: "LOBBY" | "QUESTION" | "RESULT" | "LEADERBOARD" | "PODIUM";
            /** Format: date-time */
            phaseEndsAt?: string | null;
            playerCount: number;
            /** @description เรียงตามอันดับ */
            players: components["schemas"]["GamePlayerView"][];
            question?: components["schemas"]["GameQuestionView"] | null;
            /**
             * Format: date-time
             * @description เวลาเริ่มนับเวลาตอบ (อาจอยู่ในอนาคตระหว่างนับ 3-2-1 ก่อนข้อแรก)
             */
            questionStartedAt?: string | null;
            /** Format: uuid */
            quizId?: string | null;
            quizTitle: string;
            /** @description สถิติและรางวัลพิเศษ — มีเฉพาะเมื่อ phase = PODIUM */
            results?: components["schemas"]["PodiumResultsView"] | null;
            /**
             * Format: date-time
             * @description เวลาของ server ใช้ชดเชยนาฬิกาเครื่องผู้ใช้
             */
            serverTime: string;
            settings: components["schemas"]["GameSettingsView"];
            /** Format: date-time */
            startedAt?: string | null;
            /** @enum {string} */
            status: "LOBBY" | "ACTIVE" | "FINISHED" | "CANCELLED";
            totalQuestions: number;
            /** @enum {string} */
            viewer: "HOST" | "PLAYER";
        };
        JoinGameDto: {
            /** @default 0 */
            avatarIndex: number;
            nickname: string;
        };
        MeDto: {
            /** @enum {string} */
            coreRole: "student" | "alumni" | "staff" | "lecturer" | "guest" | "admin";
            /** @description same as id — Global Identity */
            coreUserId: string;
            email: string;
            /** @description Core Hub user id (token sub) */
            id: string;
            permissions: string[];
            session: components["schemas"]["MeSessionDto"];
            /** @enum {string} */
            subsystemRole: "PLAYER" | "HOST" | "ADMIN";
        };
        MeSessionDto: {
            /**
             * @description เวลาหมดอายุของ token/คุกกี้ session (ISO 8601 จาก exp) — frontend ใช้ต่ออายุล่วงหน้าผ่าน /auth/login
             * @example 2026-10-03T09:15:00.000Z
             */
            expiresAt: string;
        };
        OptionInputDto: {
            /**
             * Format: uuid
             * @description id เดิม (ถ้ามี) — ไม่ส่ง = ตัวเลือกใหม่
             */
            id?: string;
            isCorrect: boolean;
            text: string;
        };
        OptionView: {
            /** Format: uuid */
            id: string;
            isCorrect: boolean;
            text: string;
        };
        PlayerGameResultView: {
            /** @description 0–100 */
            accuracy: number;
            avatarIndex: number;
            /** @description รางวัลพิเศษที่ได้ในเกมนี้ */
            awards: ("fastest" | "streak" | "accuracy")[];
            correct: number;
            /** Format: date-time */
            finishedAt: string;
            /**
             * Format: uuid
             * @description id ของห้องเกม
             */
            id: string;
            incorrect: number;
            nickname: string;
            playerCount: number;
            /** Format: uuid */
            playerId: string;
            questionCount: number;
            quizTitle: string;
            /** @description อันดับในห้อง (คะแนนเท่ากันได้อันดับเดียวกัน) */
            rank: number;
            score: number;
            /** Format: date-time */
            startedAt?: string | null;
            /** @description หมดเวลา หรือไม่ได้ตอบ */
            timeout: number;
        };
        PlayerGameReviewView: {
            /** @description 0–100 */
            accuracy: number;
            answers: components["schemas"]["AnswerReviewView"][];
            avatarIndex: number;
            /** @description เวลาตอบเฉลี่ยของข้อที่ตอบ (มิลลิวินาที) */
            averageResponseMs: number;
            /** @description รางวัลพิเศษที่ได้ในเกมนี้ */
            awards: ("fastest" | "streak" | "accuracy")[];
            correct: number;
            /** Format: date-time */
            finishedAt: string;
            /**
             * Format: uuid
             * @description id ของห้องเกม
             */
            id: string;
            incorrect: number;
            /** @description ตอบถูกติดกันยาวที่สุด */
            maxStreak: number;
            nickname: string;
            playerCount: number;
            /** Format: uuid */
            playerId: string;
            questionCount: number;
            quizTitle: string;
            /** @description อันดับในห้อง (คะแนนเท่ากันได้อันดับเดียวกัน) */
            rank: number;
            score: number;
            /** Format: date-time */
            startedAt?: string | null;
            /** @description หมดเวลา หรือไม่ได้ตอบ */
            timeout: number;
        };
        PlayerStatsView: {
            /** @description ความแม่นยำเฉลี่ยต่อเกม 0–100 */
            averageAccuracy: number;
            awardsEarned: number;
            bestRank?: number | null;
            bestScore: number;
            /** @description ตอบถูกติดกันยาวที่สุดในเกมเดียว */
            bestStreak: number;
            gamesPlayed: number;
            /** Format: date-time */
            lastPlayedAt?: string | null;
            /** @description จำนวนครั้งที่ติด 3 อันดับแรก */
            podiumFinishes: number;
            totalCorrect: number;
            totalQuestions: number;
            totalScore: number;
            /** @description จำนวนครั้งที่ได้อันดับ 1 */
            wins: number;
        };
        PodiumAwardView: {
            /** @enum {string} */
            kind: "fastest" | "streak" | "accuracy";
            /** Format: uuid */
            playerId: string;
            /** @description จำนวนข้อ (fastest/streak) หรือเปอร์เซ็นต์ (accuracy) */
            value: number;
        };
        PodiumPlayerStatsView: {
            /** @description ข้อที่ตอบจริง (ไม่นับหมดเวลา) */
            answered: number;
            correct: number;
            /** @description จำนวนข้อที่ตอบถูกเร็วที่สุดในห้อง */
            firstCorrect: number;
            /** @description ตอบถูกติดกันยาวที่สุด */
            maxStreak: number;
            /** Format: uuid */
            playerId: string;
        };
        PodiumResultsView: {
            awards: components["schemas"]["PodiumAwardView"][];
            players: components["schemas"]["PodiumPlayerStatsView"][];
        };
        QuestionInputDto: {
            /**
             * @default MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /**
             * Format: uuid
             * @description id เดิม (ถ้ามี) — ไม่ส่ง = คำถามใหม่
             */
            id?: string;
            /** @description ลิงก์รูปภาพ https:// เท่านั้น */
            imageUrl?: string | null;
            options: components["schemas"]["OptionInputDto"][];
            /** @description 0 = ไม่คิดคะแนน */
            points: number;
            /** @description แบบร่างเว้นว่างได้ แต่เผยแพร่ต้องมี */
            prompt: string;
            /**
             * Format: uuid
             * @description คัดลอกมาจากคำถามในคลังข้อไหน
             */
            sourceBankItemId?: string | null;
            tags?: string[];
            /** @description วินาที */
            timeLimit: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "TRUE_FALSE";
        };
        QuestionView: {
            /** @enum {string} */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** Format: uuid */
            id: string;
            imageUrl?: string | null;
            /** @description ปัญหาที่ต้องแก้ก่อนเผยแพร่ (ว่าง = ครบ) */
            issues: string[];
            options: components["schemas"]["OptionView"][];
            /** @description ลำดับเริ่มที่ 1 */
            order: number;
            points: number;
            prompt: string;
            /** Format: uuid */
            quizId: string;
            /** Format: uuid */
            sourceBankItemId?: string | null;
            tags: string[];
            timeLimit: number;
            /** @enum {string} */
            type: "MULTIPLE_CHOICE" | "TRUE_FALSE";
        };
        QuizSummaryView: {
            /** Format: date-time */
            createdAt: string;
            description: string;
            /** Format: uuid */
            id: string;
            /** @description จำนวนข้อที่ยังไม่ครบ */
            incompleteCount: number;
            ownerCoreUserId: string;
            questionCount: number;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
            title: string;
            /** @description เวลาตอบรวมทุกข้อ (วินาที) */
            totalTimeLimit: number;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        QuizView: {
            /** Format: date-time */
            createdAt: string;
            description: string;
            /** Format: uuid */
            id: string;
            /** @description จำนวนข้อที่ยังไม่ครบ */
            incompleteCount: number;
            ownerCoreUserId: string;
            questionCount: number;
            questions: components["schemas"]["QuestionView"][];
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "ARCHIVED";
            title: string;
            /** @description เวลาตอบรวมทุกข้อ (วินาที) */
            totalTimeLimit: number;
            /** Format: date-time */
            updatedAt: string;
            version: number;
        };
        ReportOptionView: {
            count: number;
            isCorrect: boolean;
            /** Format: uuid */
            optionId: string;
            text: string;
        };
        ReportPlayerView: {
            /** @description 0–100 */
            accuracy: number;
            /** @description รูปโปรไฟล์ที่ผู้เล่นเลือก */
            avatarIndex: number;
            /** @description เวลาตอบเฉลี่ยของข้อที่ตอบ (มิลลิวินาที) */
            averageResponseMs: number;
            /** @description null = ผู้เล่นที่เข้าด้วยบัตรเข้าห้อง (ไม่ได้ล็อกอิน) */
            coreUserId?: string | null;
            correct: number;
            incorrect: number;
            nickname: string;
            /** Format: uuid */
            playerId: string;
            rank: number;
            score: number;
            timeout: number;
        };
        ReportQuestionView: {
            correctAnswers: number;
            /** @description 0–100 */
            correctRate: number;
            incorrectAnswers: number;
            options: components["schemas"]["ReportOptionView"][];
            prompt: string;
            /** Format: uuid */
            questionId: string;
            /** @description ลำดับเริ่มที่ 1 */
            questionNumber: number;
            timeLimit: number;
            timeoutAnswers: number;
            totalAnswers: number;
            type: string;
        };
        SubmitAnswerDto: {
            /**
             * Format: uuid
             * @description ตัวเลือกของคำถามข้อปัจจุบัน
             */
            optionId: string;
        };
        UpdateBankItemDto: {
            /**
             * @default MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** @description ลิงก์รูปภาพ https:// เท่านั้น */
            imageUrl?: string | null;
            options?: components["schemas"]["OptionInputDto"][];
            /** @description 0 = ไม่คิดคะแนน */
            points?: number;
            /** @description แบบร่างเว้นว่างได้ แต่เผยแพร่ต้องมี */
            prompt?: string;
            tags?: string[];
            /** @description วินาที */
            timeLimit?: number;
            /** @enum {string} */
            type?: "MULTIPLE_CHOICE" | "TRUE_FALSE";
        };
        UpdateQuizDto: {
            description?: string;
            /** @description ชุดคำถามทั้งหมดตามลำดับ (แทนที่ของเดิมทั้งชุด) */
            questions?: components["schemas"]["QuestionInputDto"][];
            /**
             * @description PUBLISHED ได้เมื่อมีคำถามอย่างน้อย 1 ข้อและครบทุกข้อ (ไม่ครบ → 409)
             * @enum {string}
             */
            status?: "DRAFT" | "PUBLISHED" | "ARCHIVED";
            title?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BankItemsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                search?: string;
                tag?: string;
                difficulty?: "EASY" | "MEDIUM" | "HARD";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankItemView"][];
                };
            };
        };
    };
    BankItemsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBankItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankItemView"];
                };
            };
        };
    };
    BankItemsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankItemView"];
                };
            };
        };
    };
    BankItemsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BankItemsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBankItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BankItemView"];
                };
            };
        };
    };
    GameHistoriesController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameResultView"][];
                };
            };
        };
    };
    GameHistoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameReviewView"];
                };
            };
        };
    };
    GameReportsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description เฉพาะเกมของแบบทดสอบนี้ */
                quizId?: string;
                /** @description ค้นในชื่อแบบทดสอบ */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameReportSummaryView"][];
                };
            };
        };
    };
    GameReportsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameReportView"];
                };
            };
        };
    };
    GameReportsController_findPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                playerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerGameReviewView"];
                };
            };
        };
    };
    GameSessionsController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ค้นห้องที่เปิดรอผู้เล่นด้วยรหัสเกม (ผู้เล่นใช้ค่านี้) · ไม่ส่ง = ห้องของฉัน (host) */
                gamePin?: string;
                status?: "LOBBY" | "ACTIVE" | "FINISHED" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description มี ?gamePin= → GameLobbyView[] (0–1 ห้อง) · ไม่มี → GameSessionSummaryView[] */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["GameLobbyView"] | components["schemas"]["GameSessionSummaryView"])[];
                };
            };
        };
    };
    GameSessionsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateView"];
                };
            };
        };
    };
    GameSessionsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateView"];
                };
            };
        };
    };
    GameSessionsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameSessionsController_advance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateView"];
                };
            };
        };
    };
    GameSessionsController_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerReceiptView"];
                };
            };
        };
    };
    GameSessionsController_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameSessionsController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJoinView"];
                };
            };
        };
    };
    GameSessionsController_removePlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                playerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GameSessionsController_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateView"];
                };
            };
        };
    };
    GuestGamesController_lobby: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ค้นห้องที่เปิดรอผู้เล่นด้วยรหัสเกม (ผู้เล่นใช้ค่านี้) · ไม่ส่ง = ห้องของฉัน (host) */
                gamePin?: string;
                status?: "LOBBY" | "ACTIVE" | "FINISHED" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GameLobbyView[] (0–1 ห้อง) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameLobbyView"][];
                };
            };
        };
    };
    GuestGamesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateView"];
                };
            };
        };
    };
    GuestGamesController_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerReceiptView"];
                };
            };
        };
    };
    GuestGamesController_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GuestGamesController_join: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameJoinView"];
                };
            };
        };
    };
    GuestGamesController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                playerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeDto"];
                };
            };
        };
    };
    GameStatsController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsView"];
                };
            };
        };
    };
    QuizzesController_list: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description ACTIVE = แบบร่างและเผยแพร่แล้ว (ไม่รวมเก็บถาวร) */
                status?: "DRAFT" | "PUBLISHED" | "ARCHIVED" | "ACTIVE";
                /** @description ค้นในชื่อและรายละเอียด */
                search?: string;
                sort?: "updatedAt" | "title" | "createdAt" | "questionCount";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizSummaryView"][];
                };
            };
        };
    };
    QuizzesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuizDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizView"];
                };
            };
        };
    };
    QuizzesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizView"];
                };
            };
        };
    };
    QuizzesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    QuizzesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuizDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizView"];
                };
            };
        };
    };
    QuizzesController_copy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizView"];
                };
            };
        };
    };
}
